### ISSUE TITLE
pages部署无法使用huggingface_cli下载，只能用workers方式部署

### ISSUE THREAD

**Issue by gansui** [yurhett/hf-proxy#4]
我查了一天，发现没法解决，因为huggingface_cli命令用HEAD方法获得Content-Length字段，作为需要下载的文件size，否则会返回失败
。问题的根源是对于pages部署，cloudflare CDN由于文件在CDN内部传递时会被压缩，因此不返回Content-Length字段，导致huggingface_cli命令执行失败。
这个问题几乎无法解决，当然也许可以用GET方法下下来获得大小，但是太耗资源。不太可行。只是作为一个结论放在这里吧。
还有一个小问题，现在huggingface的cdn地址后缀换成了hf.co，需要在代码中改过来

**Comment by gansui** [comment]
comment

**Comment by yurhett** [comment]
有空我会确认这些问题 已经打算重构代码了 之前没考虑到竟然有这么多人在用

**Comment by JunkuiZhang** [comment]
> 有空我会确认这些问题 已经打算重构代码了 之前没考虑到竟然有这么多人在用

大佬能重构真是太好了。我有个问题，就是不清楚能不能只使用一个worker？我之前用worker搭的DockerHub的代理只用设置一个worker就可以。如果大佬需要的话，我可以提供这个代理的worker的脚本

**Comment by yurhett** [comment]
已修复 欢迎测试

**Comment by JunkuiZhang** [comment]
谢谢大佬!
